question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.", "answer": "False"},
    {"text": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.", "answer": "False"},
    {"text": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.", "answer": "True"},
    {"text": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.", "answer": "True"},
    {"text": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.", "answer": "True"},
    {"text": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ", "answer": "True"},
    {"text": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.", "answer": "True"},
    {"text": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.", "answer": "False"},
    {"text": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.", "answer": "True"},
    {"text": "&quot;Minions&quot; was released on the June 10th, 2015.", "answer": "False"},
    {"text": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.", "answer": "True"},
    {"text": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.", "answer": "False"},
    {"text": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.", "answer": "False"},
    {"text": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.", "answer": "False"},
    {"text": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.", "answer": "False"},
    {"text": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.", "answer": "True"},
    {"text": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ", "answer": "True"},
    {"text": "George Lucas directed the entire original Star Wars trilogy.", "answer": "False"},
    {"text": "&quot;Minions&quot; was released on the June 10th, 2015.", "answer": "False"},
    {"text": "Actor Tommy Chong served prison time.", "answer": "True"}
]
